version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "03:52"
      timezone: America/Chicago
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "03:52"
      timezone: America/Chicago
    open-pull-requests-limit: 20
