---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: cron
      cronjob: "4 4 * * *"
      timezone: America/Chicago
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: cron
      cronjob: "4 4 * * *"
      timezone: America/Chicago
    open-pull-requests-limit: 20
    allow:
      - dependency-type: all
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: cron
      cronjob: "4 4 * * *"
      timezone: America/Chicago
    open-pull-requests-limit: 20
