name: "Deploy"
description: "Deploy to Rails server"
runs:
  using: "composite"
  steps:
    - name: Set up key for SSHing to server
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        echo "${{ inputs.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        echo "${{ inputs.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
        sudo chmod 600 ~/.ssh/id_ed25519
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519

    - name: Rename 'output/' to 'blog/'
      shell: bash
      run: mv output blog

    - name: Copy 'blog/' directory to server
      shell: bash
      run: scp -r blog "${{ inputs.SERVER_USER_AND_IP }}:/root/david_runger"
